FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-24.04

RUN mkdir -p /home/vscode/.codex && chown -R vscode:vscode /home/vscode/.codex
RUN mkdir -p /home/vscode/.config && chown -R vscode:vscode /home/vscode/.config
