name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup clangd-tidy
        run: |
          sudo apt install clangd-18
          pipx install clangd-tidy==1.0.0
      - name: Run clang-format
        run: |
          shopt -s globstar
          clang-format --dry-run -Werror src/**/*.hpp test/unittest/**/*.cpp test/oj/**/*.cpp
      - name: Run cmake
        run: |
          mkdir build
          cd build
          cmake ../test -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++
      - name: Run clangd-tidy
        run: |
          shopt -s globstar        
          clangd-tidy -v --clangd-executable clangd-18 -p invalid src/**/*.hpp test/**/*.cpp
