name: Unittest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [g++, clang++]
        extensions: [ON, OFF]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: run unittest
        run: |
          mkdir build
          cd build
          cmake ../test -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_EXTENSIONS=${{ matrix.extensions }}
          make
          ./unittest
        env:
          GTEST_COLOR: "1"
