name: Unittest

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: run unittest
        run: |
          mkdir build
          cd build
          cmake ../test -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          make
          ./unittest
        env:
          GTEST_COLOR: "1"
